version: "3"
services:
  web:
    build:
        context: .
    command: /bin/sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node
    networks:
      - default
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: data
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8081:80'
    volumes:
      - /sessions
    networks:
      - default
networks:
  default:

